defaults:
    - agent: maddpg

# Experiment Settings
# Should be consistent with the layout of save_dirs
env: cramped_room
# env: forced_coordination
episode_length: 500
discrete_action_space: true

test_times: 10
experiment: vanilla
seed: 0
num_seed_steps: 10000

num_train_steps: 2.5e5
replay_buffer_capacity: 5e4

eval_frequency: 100000
num_eval_episodes: 3

common_reward: true

ou_exploration_steps: ${num_train_steps}
ou_init_scale: 0.3
ou_final_scale: 0

device: cuda

# Logging Settings
log_frequency: 5000
log_save_tb: true
save_video: true
render: false

# Save Buffer
save_model: false
save_replay_buffer: false


# save_dirs: /path/to/your_model_dir/Overcooked-AI/experiment/2024.08.05/maddpg_forced_offline-vanilla
save_dirs: /path/to/your_model_dir/Overcooked-AI/experiment/2024.08.05/maddpg_cramped_offline-vanilla

# hydra configuration
hydra:
    run:
        dir: ./experiment/${now:%Y.%m.%d}/${now:%H%M}_${agent.name}_${experiment}